<center><h1>Language Modelling </h1></center>

### Reading the data file

In [1]:
import numpy as np
from collections import Counter

### Constructing the bigrams in the corpus

In [12]:
file = open('/home/Tesla/Programming/Computational_Lingustics/Data_Sets/mothergoosecorpus.txt')
file1 = open('/home/Tesla/Programming/Computational_Lingustics/Data_Sets/mothergoosecorpus.txt').read()
bigrams = []; c = {};
for f in file:
    a = f.split()
    for i in range(len(a)-1):
        bigrams.append(a[i]+" "+a[i+1])
c = dict(Counter(bigrams))
print(file1)

<s> peter piper picked a peck of pickled peppers </s>
<s> a peck of pickled peppers peter piper picked </s>
<s> if peter piper picked a peck of pickled peppers </s>
<s> where s the peck of pickled peppers peter piper picked </s>



### Table of Probabilites

In [15]:
probabilties = {}
for i in list(c.keys()):
    probabilties[i] = c[i]/file1.count(i.split()[0])
print(c,'\n''\n',probabilties)

{'<s> peter': 1, 'peter piper': 4, 'piper picked': 4, 'picked a': 2, 'a peck': 3, 'peck of': 4, 'of pickled': 4, 'pickled peppers': 4, 'peppers </s>': 2, '<s> a': 1, 'peppers peter': 2, 'picked </s>': 2, '<s> if': 1, 'if peter': 1, '<s> where': 1, 'where s': 1, 's the': 1, 'the peck': 1} 

 {'<s> peter': 0.25, 'peter piper': 1.0, 'piper picked': 1.0, 'picked a': 0.5, 'a peck': 1.0, 'peck of': 1.0, 'of pickled': 1.0, 'pickled peppers': 1.0, 'peppers </s>': 0.5, '<s> a': 0.25, 'peppers peter': 0.5, 'picked </s>': 0.5, '<s> if': 0.25, 'if peter': 1.0, '<s> where': 0.25, 'where s': 1.0, 's the': 0.07692307692307693, 'the peck': 1.0}


### Comment

In [23]:
unique = list(set(file1.split()))
bigrams_count = np.zeros([len(unique),len(unique)], dtype = int)
for i in range(len(unique)):
    for j in range(len(unique)):
        if unique[i]+" "+unique[j] in c.keys():
            bigrams_count[i][j] += c[unique[i]+" "+unique[j]]
print(unique,'\n\n',bigrams_count)

['s', 'picked', 'of', 'if', 'piper', 'where', '<s>', 'pickled', 'a', 'peck', '</s>', 'peppers', 'peter', 'the'] 

 [[0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 2 0 2 0 0 0]
 [0 0 0 0 0 0 0 4 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 4 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 4 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0 0]
 [0 0 4 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 2 0 2 0]
 [0 0 0 0 4 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0]]


### Count of counts

In [45]:
a,b = np.unique(bigrams_count,return_counts = True)
c_count = dict(zip(a,b))
c_count,a

({0: 178, 1: 8, 2: 4, 3: 1, 4: 5}, array([0, 1, 2, 3, 4]))

From the above count on counts dictionary, we conclude that there are no missing counts.

### Good Turing Dicounting


In [46]:
c_star = []
for i in range(len(a)-1):
    c_star.append((a[i]+1)*b[i+1]/b[i])
c_star

[0.0449438202247191, 1.0, 0.75, 20.0]

### Probability of a missing bigram

In [49]:
print('Probability of missing bigram:',b[1]/np.size(bigrams_count))

Probability of missing bigram: 0.04081632653061224


### Purpose of smoothing the counts of counts table

We carried out this technique to account for the infrequent bigrams or n-grams in the data set. Basically, we are redistributing the probability mass function from frequent bigrams to infrequent bigrams. 